---
- name: Firewall Open Port for Webserver
  when: ansible_distribution == 'Rocky'
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Install Apache Web Server
  when: ansible_distribution == 'Rocky'
  yum:
    name: 'httpd'
    state: latest

- name: start apache
  ansible.builtin.service:
    name: httpd 
    state: started

