---
- name: Update 
  hosts: all
  become: yes
  roles:
    - common
    
- name: Setup Apache
  hosts: webservers
  become: yes
  roles:
    - apache

- name: Setup MySQL
  hosts: dbservers
  become: yes
  roles:
    - mysql