---
- name: Install MySQL on webservers
  when: ansible_distribution == 'Rocky'
  yum:
    name: 'mysql-server'
    state: latest
    
- name: Firewall Open Port for Database
  ansible.posix.firewalld:
    service: mysql
    state: enabled
    permanent: true
    offline: true

- name: Start MySQL
  ansible.builtin.service:
    name: mysqld
    state: started