---
- name: Install EPEL release package
  ansible.builtin.yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
    disable_gpg_check: true  

- name: Install Remi Repository RPM
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Enable Remi PHP 8.1 Module
  ansible.builtin.command:
    cmd: dnf module enable -y php:remi-8.1
  changed_when: true

- name: Install PHP 8.1 and required extensions
  ansible.builtin.yum:
    name:
      - php-fpm
      - php-common
      - php-mbstring
      - php-xmlrpc
      - php-soap
      - php-gd
      - php-xml
      - php-intl
      - php-mysqlnd
      - php-cli
      - php-zip
      - php-curl
    state: present